### ISSUE TITLE
How to get current setting and status of ZTE F680

### ISSUE THREAD

**Issue by LeoI5** [jazzran/ZTEF680_Wifi_En#5]
Project is great! Nice job!

I want to get status of incoming phone call (VoIP Register Status).
Could you explain how to get current setting and status of ZTE F680?
If I undestand corectly you only write new setting to F680.
According [this](https://gist.github.com/aldoridhoni/bcefbaeab544ec544910fd0126cf5f46#file-tree-bin) there is some pages with the status F680.

Thx
Leonid

**Comment by jazzran** [comment]
Hi, sorry for the late response.

As I answered in another issue, I don't have anymore the ZTE F680 available, so, unless there is a list of available commands that can be sent to the router, it will be impossible for me to obtain the URL/command to be called.

With the list you have shared maybe calling this url will report something http://x.x.x.x/getpage.gch?pid=1002&nextpage=pon_voip_sipqos_js.gch, but it is only a guess

**Comment by LeoI5** [comment]
> Hi, sorry for the late response.
> 
> As I answered in another issue, I don't have anymore the ZTE F680 available, so, unless there is a list of available commands that can be sent to the router, it will be impossible for me to obtain the URL/command to be called.
> 
> With the list you have shared maybe calling this url will report something http://x.x.x.x/getpage.gch?pid=1002&nextpage=pon_voip_sipqos_js.gch, but it is only a guess

Many thanks for look vector!
I found it - status_voip_4less_t.gch
